### ISSUE TITLE
Rendering at High Speed Drastically Decreases Performance

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio/evolv.io#114]
When rendering at high speed (32x+ usually) there is a huge performance decrease, as it is trying to render everything that's going on so fast, along with all of the steps, so I've setup an if statement around certain areas to say that if `evoBoard.playSpeed <= 16` it will render.
Otherwise, it will skip rendering.
This effectively stops rendering if the speed is 32x or higher.

This change actually drastically improves FPS at 64x speed.

Edit: It appears `evoBoard.playSpeed` is now `evoBoard.getPlaySpeed()`

**Comment by NateUniAccount** [comment]
Do we want to stop rendering? Or just prevent it going faster than it can handle?

**Comment by UnknownEvil** [comment]
At the moment mine just skips rendering the board when you set the speed to 32x or higher.

**Comment by UnknownEvil** [comment]
Perhaps just an option to toggle rendering of the board, perhaps in place of the "This button does nothing" button.

(Because the screenshot doesn't work if it doesn't render the board)
