### ISSUE TITLE
Fighting Almost Never Happens (timeStep *= 100)

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio/evolv.io#118]
Fighting almost never happens because on `line 44` in `CreatureAction.java` it multiplies `timeStep by 100` / `timeStep *= 100` remove it, and voila, on occasion a creature will attack. I mentioned this in #59

**Comment by NateUniAccount** [comment]
Good catch!

**Comment by NateUniAccount** [comment]
Merged so closing this issue
