### ISSUE TITLE
What is the intended scope of the Readme?

### ISSUE THREAD

**Issue by AutumnRayne** [evolvio/evolv.io#12]
In short, should the Readme include some basic use of the game, or should a user guide be made into a separate file?

Furthermore, would it be helpful and/or useful if I made a list of simple variable changes that can be tweaked to elicit different behaviours of the system?

I'm perfectly happy to write said guide--I just need to know whether it should be a part of the readme or a new file entirely.

**Comment by israelraizer** [comment]
I think it should be a new file...

**Comment by mbertheau** [comment]
You can do it both ways, I don't think there will be unsolvable problems either way. You could write a short teaser text in the readme file and link from it to the detailed guide.

**Comment by YoYoYonnY** [comment]
For right now I don't think anything beyond a mention in the README is necessary.

**Comment by YoYoYonnY** [comment]
But if anyone would take it upon themselves to write one, that would be great.

**Comment by mbertheau** [comment]
The question is answered so I'll close this.

@AutumnRayne I'm very much looking forward to the guide! :)
