### ISSUE TITLE
Old Creatures Disappear?

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio/evolv.io#127]
![evolviobug](https://cloud.githubusercontent.com/assets/12143899/24174455/04466c4a-0e67-11e7-9f6a-5b0b73fdcf7c.png)

- It's only happening in this list (Oldest), Biggest, Youngest, Etc. are unaffected
- Selecting them takes you to some unknown location?

**Comment by NateUniAccount** [comment]
It looks like somethings wrong with the rendering with that...there should be a creature shown to the left of the top creature information in the UI on the right

**Comment by NateUniAccount** [comment]
Looks the same bug as in #52

**Comment by UnknownEvil** [comment]
Yeah, thanks for catching that, I heaven't read all of the other issues.
