### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by CrazyPython** [evolvio/evolv.io#13]
A linter could do quite a bit.

**Comment by YoYoYonnY** [comment]
See 84ef3861a16b98796d7d10330f26a1ffa759a915 and 7ad2c2060a9c59ef6262d239737cdf3eebd10750

**Comment by YoYoYonnY** [comment]
Do you have any suggestions as to how we could better clean up the code?

**Comment by izik1** [comment]
hmm we could go check for a automated styling convention like http://checkstyle.sourceforge.net/ (i don't know if that one is any good)

**Comment by CrazyPython** [comment]
@YoYoYonnY my research shows that there is a processing linter available. I don't have Processing IDE (required to run it), but surely many of you do. [see this issue](https://github.com/bvoq/linter-processing/issues/3)

**Comment by mbertheau** [comment]
That's just a syntax check, calling it a linter is a misnomer in my opinion. We already use that approach in the Circle CI integration, see [circle.yml](../blob/master/circle.yml).

**Comment by SerayaEryn** [comment]
What do you think about the MVC pattern? It might be good to add a bit more structure to the code and classes would become smaller and easier to understand.

**Comment by CrazyPython** [comment]
@mbertheau Ah, Id idn't look into the source - it said it was a linter and I believed it.

**Comment by CrazyPython** [comment]
@SerayaEryn MVC. No. iOS hell right there. MVC is fine, but don't do complex interactions like apple does - just use simple methods.

**Comment by mbertheau** [comment]
MVC would be a step in the right direction, but we shouldn't religiously follow the pattern. Elements of FRP would also make a lot of sense for this kind of application.

**Comment by SirSKillz** [comment]
Is it alright if I close this seeing as there has been a clean up and not much has been discussed in here for some time?

**Comment by mbertheau** [comment]
I agree. This issue is not very specific as to what should be done.
