### ISSUE TITLE
I made an improvement to Evolvio.

### ISSUE THREAD

**Issue by israelraizer** [evolvio/evolv.io#14]
Remember that button saying "This button does nothing"? Well, now it actually does something, it toggles grid drawing on and off so that the simulation can run faster.

In file Board.pde:
-add another boolean variable called fastDraw around line 42, right next to userControl
<code>boolean userControl, fastDraw;</code>

-initialize it to false in the Board constructor method around line 99(you can also set userControl to false to make the creatures control themselves as soon as the simulation starts)
<code>fastDraw=false;</code>
<code>userControl=false;</code>

-change the text of the button around line 210 so that it describes it's function correctly.
<code>String[] buttonTexts = {"Brain Control","Maintain pop. at "+creatureMinimum,
      "Screenshot now","-   Image every "+nf((float)imageSaveInterval,0,2)+" years   +",
      "Text file now","-    Text every "+nf((float)textSaveInterval,0,2)+" years    +",
      "-    Play Speed ("+playSpeed+"x)    +",fastDraw?"Normal":"Fast Forward"};</code>

In file EvolvioColor.pde:
-add an else if statement around line 157 after the if(buttonNum==6) block is closed to allow clicking the button to change the variable
<code>else if(buttonNum==7){
          evoBoard.fastDraw=!evoBoard.fastDraw;
        }</code>

-surround the statement around line 73 that calls drawBoard method with an if to execute it only when fastDraw is disabled
<code>if(!evoBoard.fastDraw){</code>

**Comment by CrazyPython** [comment]
@israelraizer Submit a pull request! select any file > pencil icon > make changes > make pull request > go to your fork > select `patch-1` branch > continue adding changes for each of the files.

**Comment by CrazyPython** [comment]
Or just clone it and `git add . ` `git commit -m "Commit message here"` `git push origin master`. But your probably don't know how to do that.

**Comment by israelraizer** [comment]
Yeah, I'm not really used to using GitHub...

**Comment by CrazyPython** [comment]
@israelraizer just do it, it's not that hard

**Comment by YoYoYonnY** [comment]
@israelraizer For small changes you can click the edit button when viewing a file, which will create a new fork. You can then send a pull request from that.

**Comment by YoYoYonnY** [comment]
@israelraizer I am closing this issue as it's invalid. You can send me a comment if you want me to set up the pull request for you.

**Comment by YoYoYonnY** [comment]
Invalid issue, closing.

**Comment by YoYoYonnY** [comment]
See #18
