### ISSUE TITLE
Allow Creatures to Change Vision Length and Angles

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio/evolv.io#152]
I've already written a form of this, but I don't know if it's actually done in the way it should be done, I'll post a picture of the results here.

![evolviobug](https://puu.sh/v4MOL/fa62c5b876.png)

Also, not sure if I accidentally made some kind of reproduction glitch, it was already like that, or it's just a side-effect of being able to change vision things?

Either way, it appears there is some kind of separation between "species".
I'm assuming it's because the creatures like to move in circles, and so they reproduce and make a giant area of them selves.

![yes](https://puu.sh/v4N3s/e859b6befe.png)

**Comment by PRabahy** [comment]
Open a pull request and let us take a look.

I implemented it a while ago (before porting to eclipse), but it never got merged. I have been thinking that it would be cool if eye vision and distance was a function of both evolution and the neural network. For example, each "eye" would have a base distance and angle. If the neural net tries to look nearer or further, it would take more energy. I'll probably implement something like this soon.

**Comment by UnknownEvil** [comment]
I don't have an energy cost for seeing certain distances, but they do work. I'll have to download the current version and re-make it but, I can do that pretty quickly.

**Comment by NateUniAccount** [comment]
Has this been committed now?

**Comment by PRabahy** [comment]
Yep, good catch. https://github.com/evolvio/evolv.io/pull/157
