### ISSUE TITLE
Decrease repo churn

### ISSUE THREAD

**Issue by PRabahy** [evolvio/evolv.io#166]
IMO, Pull Requests are the proper place to discuss and make small changes to files. When I pulled I just got 52 new commits that only touched ~3 files. I believe that all that churn would have been much better handled in a very small number of commits that after having a proper discussion in a pull request.

**Comment by PRabahy** [comment]
I guess the other thing that bugs me is that I feel that the 52 commits are actually heading in the wrong direction. Github already has a roadmap (https://github.com/evolvio/evolv.io/projects) and tasklist (https://github.com/evolvio/evolv.io/issues). I don't see any reason on replacing those with less functional versions of text documents that we keep in the repo.

**Comment by NateUniAccount** [comment]
Have been thinking about that too and wondering whether it was the right thing to do, in hindsight I'd have done it all in one PR, and probably not done it in the first place anyway. Will probably revert them all once I find out how.

**Comment by NateUniAccount** [comment]
Have reopened the issues that were closed

**Comment by NateUniAccount** [comment]
OK have put everything back to how it was, it's just the large commit history that is still there. I tried doing a revert but couldn't work out how to do multiple reverts. There's always the possibility of doing a reset which may be ok as it's not been that long, but it's still public so didn't fancy doing that without discussing it.

**Comment by PRabahy** [comment]
Looks like we are all on the same page now. Closing.
