### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kodomazer** [evolvio/evolv.io#167]
As alluded to in the discussion in #166 we have [Projects](https://github.com/evolvio/evolv.io/projects/1) to help us organize our road map for where we want this to go.

I've started the process by making the project (Which I've been meaning to for a while).  Any thoughts?

**Comment by NateUniAccount** [comment]
Looks good! Is it possible to rename it to something like Code Quality as it looks like all the items are to do with that

**Comment by NateUniAccount** [comment]
Closing as the projects have been transferred
