### ISSUE TITLE
Create a gitter chat room

### ISSUE THREAD

**Issue by IHaveADrone** [evolvio/evolv.io#17]
Having a chat room for the project would be better than using comments on issues to communicate.

https://gitter.im

**Comment by Cody-Soultz** [comment]
I would assume a slack would me more appropriate
https://slack.com/

**Comment by IHaveADrone** [comment]
how so?

**Comment by Cody-Soultz** [comment]
More so I guess I have had experiences with slack in larger groups not gitter. That being said I haven't seen to much gitter, but I have used slack quite often. I guess it is a matter of if this is going to feel more like a team or more like an open source community. Which after a 30 min google search I think for something like this an open community is the feeling we want therefore a gitter would probably be better than a slack.

**Comment by CraigBanach** [comment]
I have created a gitter.im chat room at: 

[https://gitter.im/evolv-io/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link]

**Comment by IHaveADrone** [comment]
@CraigBanach

**Comment by IHaveADrone** [comment]
@CraigBanach can you please delete your chat so we can make an official one

**Comment by CrazyPython** [comment]
StackExchange chat interface is good too - simple, casual, good for code

**Comment by mbertheau** [comment]
https://github.com/evolvio/evolv.io/pull/22

A little later I will find time to clean up #22 so that the chat room appears in the README.

**Comment by mbertheau** [comment]
Done in https://github.com/evolvio/evolv.io/commit/e831fc2ae37a8df0c31025077ba0cdc944e4c9dc
