### ISSUE TITLE
Maven Not Showing up in Elipse

### ISSUE THREAD

**Issue by Dman1904** [evolvio/evolv.io#185]
I followed the steps of how to execute it up to step 3, it says to click

> File > New > Project > Maven > Check out Maven Projects from SCM > Next

Except, I can't seem to find Maven, I don't know if there is more I need to download or something. If someone could help that would be great.

**Comment by UnknownEvil** [comment]
Do you have Eclipse Neon for Java Developers? Mine seemed to work fine. That's the only problem I could foresee.

**Comment by NateUniAccount** [comment]
It sounds like you may need to install the Maven plugin for Eclipse. Try going through the first answer from here
http://stackoverflow.com/questions/8620127/maven-in-eclipse-step-by-step-installation

**Comment by NateUniAccount** [comment]
Oh by the way if you could let us know whether it works or not that would be great :)

**Comment by Dman1904** [comment]
@NateUniAccount It worked! Except I accidentally clicked a couple things and deleted stuff I shouldn't have deleted. After that whole meltdown of my computer, I am trying again.

**Comment by Dman1904** [comment]
Oh no, there is another problem, when I go to 

> Run > Run

As it says on step 10 there is a pop-up that says 

> The selection cannot be launched, and there are no recent launches.

**Comment by NateUniAccount** [comment]
That sounds like it hasn't got any run configurations yet. There are at least 2 ways of doing that.

Easy way:
Open the EvolvioColor class
Click the run button
If it asks how to run it, click on "As a Java Application"

Flexible way:
Click Run -> Run Configurations, this will open a new window
In the left hand side click on "Java Application"
Near the top left, click on the top left icon which says "New launch configuration"
Change the name if you want
Under the section "Main class:" click the "Search..." button to show a list of classes with a main method in
Double click on EvolvioColor
Click Apply then Run

Note to stop the simulation you can press the Escape key

Press the drop down arrow to the right of the Run icon to show a list of the recent run configurations

**Comment by Dman1904** [comment]
Thank you so much!
