### ISSUE TITLE
Opinions on this design vs. the current one

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio/evolv.io#188]
This is just with white outlines around lots of rectangles.

Edit: Increased button width to match list width, center button labels again, but made it dynamic in the code this time.

Edit 2: Rounded Rectangles and creature scaling

# Updated 
![Update](https://puu.sh/xnCsA/ed2cf9cf04.png)

# Previous
![Outlines](https://puu.sh/xh0dz/f67c52b215.png)

**Comment by PRabahy** [comment]
UI is not my strongest suit. Looks reasonable enough.

**Comment by UnknownEvil** [comment]
Obviously there are tweaks I can make, etc. I'd like to do rounded rectangles, but I either have to draw 4 circles and 2 rectangles for it, or find some built in method.

**Comment by NathanJAdams** [comment]
For rounded rectangles, in the Board.drawUI() method where it's calling EvolvioColor.rect() the rect() method can take a 5th parameter which will be the rectangles corner radius

**Comment by UnknownEvil** [comment]
Oh, really?

**Comment by NateUniAccount** [comment]
Anytime :)

**Comment by NateUniAccount** [comment]
The rounding does look a lot better!

**Comment by UnknownEvil** [comment]
Yeah, I've changed a bunch of other things so I've gotta do this on a clean copy before I do a PR. I'll probably do a separate PR for the selected creature UI

**Comment by UnknownEvil** [comment]
Created PR
