### ISSUE TITLE
CONTRIBUTING.md for newcomers

### ISSUE THREAD

**Issue by YoYoYonnY** [evolvio/evolv.io#26]
A `CONTRIBUTING.md` or `HACKING.md` contains information for anyone who wishes to contribute to the project. A CONTRIBUTING.md might include the following:
- How to write an issue
- How to write a commit
- How to submit a pull request
- How to build and execute tests
- What configuration to use for git
- What configuration to use for your editor

**Comment by mbertheau** [comment]
Collecting the information for this:

- use the Autoformat menu item in the processing after you make changes to make sure indentation is correct
- maybe incorporate info from this comment: https://github.com/evolvio/evolv.io/issues/8#issuecomment-251843352 and this comment: https://github.com/evolvio/evolv.io/pull/9#issuecomment-251838904
- if you're new to git and/or GitHub, try the GitHub Desktop application on desktop.github.com

**Comment by YoYoYonnY** [comment]
See #31

**Comment by YoYoYonnY** [comment]
I recommend following the work flow of https://github.com/nodejs/node

**Comment by NateUniAccount** [comment]
Initial file has been posted
