### ISSUE TITLE
Force push to make history linear and clean

### ISSUE THREAD

**Issue by YoYoYonnY** [evolvio/evolv.io#38]
I just force pushed to make history linear, to remove redundant branches, and in general just to clean things up. If you have forked the repository before I would recommend forking again. Pull requests should also be resubmitted. Use this thread for any problems you came across.

**Comment by mbertheau** [comment]
I'm sorry @YoYoYonnY, but this is no way to treat contributors and respect the amount of work they put into this project. It's not ok to rewrite all history and then tell everybody else to re-do their PR. At the very least changes like this require notice to and discussion with other contributors and community members.

I will restore master to the state it was in before this change and reopen relevant PRs and issues.

**Comment by YoYoYonnY** [comment]
@mbertheau There were only 2 PR and both of them already had merge conflicts. I tried to do it as fast as possible after the last PR had been merged, to avoid people having an invalid fork. Looking at https://github.com/evolvio/evolv.io/network, the only corrupted fork is by https://github.com/jocopa3.

**Comment by mbertheau** [comment]
Still, I find such an action acceptable only in a closed environment where you can notify all relevant people and possibly help them / do for them the work that a history rewrite creates. I don't find it acceptable here, where people have possible local modifications that they haven't yet put in a public fork on github, where there's people that use git and/or github for the first time, or that don't have the experience it takes to handle a history rewrite, or to resubmit a PR without manually doing all the source changes again.

**Comment by YoYoYonnY** [comment]
@mbertheau Most forks are not affected, though. Only those which were forked from a removed/squashed commit, and those that use separate branches.

**Comment by mbertheau** [comment]
git and GitHub understands that the old and the force-pushed master are not the same, even though the represent the same source code. See for example at the bottom of #18 the tooltip on the button to re-open the PR. It says here "israelraizer:patch-1 has no history in common with evolvio:master`. This was true during the time of the force-pushed master branch. It's not true anymore now since the old master has been restored, but GitHub still doesn't allow re-opening the PR.

**Comment by NateUniAccount** [comment]
Wow dude, it's meant to be a collaboration lol Not trying to pile on here but having a detailed history is actually a good thing, it means if a mistake is made we could go back to whatever stage we want. In general it's best to make things as easy as possible for fellow contributors rather than making them jump through hoops.
@mbertheau Totally agree with having a discussion before doing major changes like this. Would it be possible to make master non-pushable and have a development branch for current work and then regularly PR to master?

**Comment by mbertheau** [comment]
Well, @YoYoYonnY rebuilt the history to retain any relevant commits and remove those that clutter the history without relevant information, mostly merge commits. I agree that that's a worthy goal. @YoYoYonnY also took precautions (see above https://github.com/evolvio/evolv.io/issues/38#issuecomment-252964183 and https://github.com/evolvio/evolv.io/issues/38#issuecomment-252969742) to minimize negative impact on the work of other contributors. We just disagree on what is acceptable negative impact, and how much communication is necessary. There also seems to be a difference in understanding how git/GitHub work in relation to history rewrites.

I agree (and @YoYoYonnY does, too, afaiu) that a detailed history is a good thing, however for me it's more about being able to tell why a specific line in the code ended up like that. Tools can show you the commit in which a specific line was last changed, which is often helpful when trying to understand the code when you want to change it.

**Comment by YoYoYonnY** [comment]
@NateUniAccount Both @mbertheau and I already explained what my goals were. I did this for the sake of the future, but also for my sanity and my future activity in this project. I never maintained a public repository before, especially one like this (with people using git, even GitHub, for the first time), so I am used to people solving their own merge conflicts before sending a pull request, keeping their own commit messages clear and easy to read, people who know when to commit (especially `commit --amend`), *Fix Force Pushes*, etc.

Now, I wouldn't have minded doing all this _for_ people, or so I thought, because as #9 thought me, it's not that easy. Using the merge button does not make things any better (See the mess caused by e.g. #31 and #32), and especially with the choice to allow unfinished pull requests, it would mean solving merge conflicts, rewriting commits, doing force pushes on the fork without messing anything up (changing contributions and commit owners, creating merge conflicts, breaking pull requests, etc.), this all multiple times per pull request, or on the many tiny pull requests like #40. Mind you, this is all a side project for me, I have other things to do, too. Rebasing the fork would allow for all this to be somewhat easier, as you can rebase, but not merge, multiple times. Now, by rebasing the _entire_ repository, it would allow me to use some nice scripts and tools I've used before to make this easy to the extent that I would like to help people solve their commits and merge conflict again (As well as, of course, cleaning up history, etc.). Furthermore, the only thing stopping me from pushing rebasing was that I had to force the push.

My reasoning for the force push at the time was that, did I force push when noone had a changed fork, I could push without affecting anyone. I expected few forks would actually be ahead of `master` (Because those most active at the time didn't have a modified fork yet, but also because there's still so few contributors), and looking at https://github.com/evolvio/evolv.io/network I was right. (Anyone who `git clone`d probably also has enough skill to fix their problems, or at to least report an issue here so I could do it for them, which was the whole reason why I created this issue in the first place).

Looking back, I probably shouldn't have force pushed anything without communicating, even if it were to be in a private project environment. However, the situation, the desperation, and especially the timing made me do it anyway. I've never had any problems with force pushes, especially like this. I really want to contribute to, even maintain this project, but at the same time, if that means spending more time doing all the above than actually contributing myself (and mind you, even if I do decide to submit commits myself, I'll still have to solve the merge conflicts, be it my own or the ones caused by me), it just becomes too much time and effort, especially when the project becomes bigger (which I really hope it does, don't get me wrong). Therefore, as it stands, I don't feel like continuing to contribute to and especially maintain this project anymore, and I don't think this will change even if the force push was reverted. This just isn't how I want to contribute to or maintain a project.

This, ironically, means you've lost your biggest contributor, not just by [LOC (Skewed, does not include my latest commit, and includes the style changes)](https://github.com/evolvio/evolv.io/graphs/contributors?from=2016-10-02&to=2016-10-15&type=a) or [commits](https://github.com/evolvio/evolv.io/graphs/contributors?from=2016-10-02&to=2016-10-15&type=c), but, more importantly, by time, effort and motivation. I still hope you guys make the best of it, and I'd like to see what has become of this project in a few years.

I will be closing this issue. With the repo reset, I don't expect anyone else to still have any problems with the force push.

**Comment by NateUniAccount** [comment]
@YoYoYonnY I feel I need to apologise for coming across as rude and patronising, that wasn't my intention at all. At the time it felt like you were treating it as your own personal project but in hindsight I can completely understand the pain of merging. I think part of the trouble stems from the classes currently being so large. When it's re-factored into smaller classes PRs will be so much easier to merge.
Listen, why don't you stay for now, it would be a shame to lose you after you've done so much. It sounds like if we all have a discussion about the best way to go forward we could get much better ideas if we all discuss it together than doing it separately. If you have different ideas and want to pull out after that then no hard feelings. What do you think?
