### ISSUE TITLE
Put "How to run" in README

### ISSUE THREAD

**Issue by CrazyPython** [evolvio/evolv.io#4]
Someone needs to figure out how to build this thing and send a PR.

**Comment by mbertheau** [comment]
The steps are:

1. Download processing.
2. Open [EvolvioColor.pde](EvolvioColor/EvolvioColor.pde) in it.
3. Click play.

Todo: Put this in the README.

**Comment by YoYoYonnY** [comment]
See 36ee7e005f99833055ee15489edd91e94e485217 and c918ea8dd2c6e3ba48ae89ae3fe0a3b8f04b553d

**Comment by YoYoYonnY** [comment]
See #20

**Comment by YoYoYonnY** [comment]
A similar request has already been committed, closing.

**Comment by YoYoYonnY** [comment]
@mbertheau I would suggest reserving the `help wanted` label for issues which are solely requests for help. Similairly `question` label should be preserved for those issues that are questions or requests. See #3.

**Comment by mbertheau** [comment]
@YoYoYonnY I agree. I guess I looked at "help wanted" from the maintainer perspective instead of the user perspective. I'll do my best :)
