### ISSUE TITLE
GitHub doesn't have fine-grained permissions

### ISSUE THREAD

**Issue by NateUniAccount** [evolvio/evolv.io#47]
This is more for debate than an issue.
GitHub doesn't have fine-grained permissions, eg. any collaborator can push to master. What would be nice would be if only the owner could write to master and everyone else could create their own branch which only they could write to.
AFAIK GitHub doesn't allow this, but BitBucket does. Basically I'm suggesting moving the repo to BitBucket to take advantage of that.
Would love your thoughts.

**Comment by PRabahy** [comment]
The permissions are nice for bitbucket, but not everyone needs permissions to the main fork. Everyone can make their own fork with just 1 click, so thats a pretty low barrier to entry. I would tend to say keep the number of people with direct commit access low and encourage people to submit PRs.

**Comment by NateUniAccount** [comment]
The issue is that AFAIK if someone can create a branch they can push to master too, AFAIK there's no way to split those two permissions. If merging between forks is easy then there's not a problem.

**Comment by NateUniAccount** [comment]
For posterity, here's how to merge fork
http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381
