### ISSUE TITLE
Lifespan

### ISSUE THREAD

**Issue by kodomazer** [evolvio/evolv.io#58]
If we add in an increased energy cost depending on how long a creature has been alive I think we can promote having offspring, and thus advance the rate of evolution.

**Comment by mbertheau** [comment]
Sounds interesting to me. There's nothing in the simulation limiting like span right now, correct?

**Comment by kodomazer** [comment]
I haven't looked too deeply, but from what I've seen from running it, there is no cap.  I've had simulations where I just get some that live for a majority of the simulation because they just eat and go in circles, so they never die and they never reproduce.  This makes it so the simulation can't automatically generate new creatures to test.

**Comment by pilger15** [comment]
I created a pull request that does exactly that

**Comment by kodomazer** [comment]
Implemented in #61 
Closing this issue.
