### ISSUE TITLE
Two fixes

### ISSUE THREAD

**Issue by AutumnRayne** [evolvio/evolv.io#6]
Issues:

1) The fight function works correctly when run via keyboard but does not appear to work when run by the AI.
2) There is a bug in the way the mouthHue output is given by the neural network, which in essence lets it evolve well below 0.0, meaning that once something has evolved to have a red mouth, it can evolve to have a "more red" mouth, making it harder for it to ever evolve away from having a red mouth. Thus we see huge populations of redmouths that take over the map but have a very hard time moving away from that color.

Fixes:

1) I may be misunderstanding exactly what the multiplication by OBJECT_TIMESTEPS_PER_YEAR is for in the Board.pde keyboard controls, but a similar modifier is missing from the AI version. As such, when I multiplied the AI version of the fight function by the same modifier (100), my AI creatures learned to fight. To make this change, go into Creature.pde, around line 190, and find this line:

    fight(neurons[end][4],timeStep);

And change it to this:

    fight(neurons[end][4],timeStep*100);

2) Basically, we just need the decimal remainder of the neural network's output. Cary saw this problem and made it so that the output is constrained so that 0 <= x <= 1. However, this means that all values above 1 are exactly 1, and all values below 0 are exactly 0 (both red). If, instead, we take the remainder, we get back to a population that can subsist across more than just the red portions of the map. So, again in Creature.pde, around line 194, find this line:

      mouthHue = Math.min(Math.max(neurons[end][10],0),1);

And change it to this:

      mouthHue = Math.abs(neurons[end][10]) % 1.0;

NOTE: Because of the absolute value function, values below 0 will move in a different direction than values above 0. I don't think this is a *big* issue, but if there is a simple way to fix it to maintain direction, it might be worth looking into as the bigger bugs are ironed out.

**Comment by mbertheau** [comment]
Thanks for your fixes! I added them in the two commits that you see above.
