### ISSUE TITLE
Trouble getting started.   

### ISSUE THREAD

**Issue by azakar** [evolvio/evolv.io#63]
Downloaded master file, after 200 years, pop minimum set to 450, not one creature ever ate or moved...  Am I doing something wrong?

**Comment by pilger15** [comment]
You have to activate "Brain Control". Just click the top left Bottom which says "Keyboard Control" to toggle between user Control and automated Control

**Comment by kodomazer** [comment]
If there are any more problems please reopen this, but I'm going to close this to reduce clutter.
