### ISSUE TITLE
[Question] Move evolv.io to eclipse

### ISSUE THREAD

**Issue by PRabahy** [evolvio/evolv.io#70]
Does anyone else have any objection or want to move to eclipse?

I would like to move to eclipse because the processing IDE keeps hanging for me. I also have not been able to successfully get the debugger working.

From my tiny bit of research, it looks like it should be pretty straight forward, but using eclipse instead of processing might raise the barrier of entry a bit. I will admit that I was very impressed with how easy it was to get the processing project up and running to make my first tweak.

**Comment by PRabahy** [comment]
Ok, I got it working! I was able to verify that the debugger actually works as expected, so my vote is to move in that direct.

**Comment by SirSKillz** [comment]
I would have to agree with you for this. While it is super convenient to run this in processing, the tools that we get from Eclipse or other Java IDEs would allow us to be much more productive in the future. I much prefer the benefit of the tools we will get from Eclipse, rather than the convenience of processing.

**Comment by PRabahy** [comment]
Looks like most of the open PRs just got merged. I'll try to do the conversion in the next day or 2 and open a new PR for it. You might want to hold off on #72 until I finish this because it will make debugging it a lot easier.

**Comment by SirSKillz** [comment]
I'll make the config file and leave it at that. Good luck.

And yeah, I like keeping as few open PRs as possible. Just wasted effort when they aren't put in.

**Comment by kodomazer** [comment]
On that note, it would be best to get all the "growing pains" out of the way early so we have a stable code base moving forward.
We should come to a consensus of what we want to do, and have someone (or a group of people) do that in a timely manner and then we can all get to work on a properly structured

**Comment by SirSKillz** [comment]
This issue was opened 28 days ago. I assume everyone who is actively working on this has seen it by now, and no one has voiced any issues. Due to this, I think it is probably safe to move forward. As @PRabahy has already started working on this, I find him to be a good choice to convert the code.

**Comment by PRabahy** [comment]
Sorry, I slacked on this over the past week. I still intend on doing it ASAP.

**Comment by PRabahy** [comment]
Ok, here are the steps that I did.

- Pull master
- Open evolve.io in Processing
- File -> Export Application ->Export
- Follow the directions on https://processing.org/tutorials/eclipse/ (minor naming tweaks)
- Open \evolv.io\EvolvioColor\application.windows64\source\EvolvioColor.java
- Overwrite EvolvioColor.java in eclipse with the contents. (minor tweaks required)
- Import Jygquip1-48.vlw
- Run with success!!!
- Copy the .git folder over into the new evolve.io directory
- Fix up the .gitignore
- Discard changes that I actually want to keep (CONTRIBUTING.md and README.md)
- Commit
- For each inner class, Refactor -> Move Type to New File
- Fix up the damage (initializers creating a evolvioColor.color were not happy)
- It still works!!
- Commit

Pull Request inbound.
