### ISSUE TITLE
Non-optimized yums calculation

### ISSUE THREAD

**Issue by Bladesmc** [evolvio/evolv.io#74]
When you downloaded the source code from Cary, did you download the version that was labelled "before optimization?" Because when I run this version of the software, 16x is too much for my computer to handle (i7 4th gen, gtx 960) but when I run Cary's optimized version I can handle 16x speed no problem. I want to use your more functional version but it's difficult to simulate many years at a time due to not being optimized.

**Comment by SirSKillz** [comment]
I'm not sure what version we downloaded, but performance has been something we have been continually working on. Hopefully performance will improve in future updates. While I haven't dealt with the issues you're describing until I get above 100X, it is a valid concern with crunching massive amounts of data. Sorry to hear about your issues. Maybe run it while you sleep?
