### ISSUE TITLE
Two more fixes

### ISSUE THREAD

**Issue by AutumnRayne** [evolvio/evolv.io#8]
Issues:

1) Just the body version of the redmouth bug. Same fix applied.
2) Notice how the populations never seem to be able to develop a response to stimulus? Turns out, when the game creates a primordial, it doesn't create a functional neural network for it. It just gives it things to multiply by the constant node. Its offspring have a functional neural network, but I suspect that it only gives the illusion of functioning, as I have never seen an offspring, even with a functional neural network, respond to a stimulus. I believe this all stems from the core issue of the primordials' neural networks being nonfunctional.

Fixes:

1) As before, find this line in Creature.pde (around 180): 

      hue = Math.min(Math.max(neurons[end][0],0),1);

Change to this:

      hue = Math.abs(neurons[end][0]) % 1.0;

2) If you look in the constructor for the creatures, you'll see that Cary, in generating the neural network from a null case (that is, the primordials) put in a particular block of code which makes all the axon values except the constant node a 0. I suspect he was intending to implement something with it later and simply forgot that he had gutted the rest of his neural network. Anyway, find this block of code in Creature.pde around line 63:

          double startingWeight = 0;  
           if(y == BRAIN_HEIGHT-1){
             startingWeight = (Math.random()*2-1)*STARTING_AXON_VARIABILITY;
           }

Replace the entire thing with:

            double startingWeight = (Math.random()*2-1)*STARTING_AXON_VARIABILITY;

Suddenly, when you run the sim, you'll see creatures responding to stimuli again! (the most easy way to tell is because they start blinking again, whereas the old version never had them change color beyond their inherent mutations. Another way to tell is that you can select a creature and watch its outputs change as inputs change, which wasn't happening at all before).

This bug is likely the reason the creatures were never developing past "eat while circling." They were unable to change once born.

**Comment by AutumnRayne** [comment]
Also, just to test that this is allowing for more complex behaviors, I've been running a few tests. In one of my tests, I now have a little guy who inverts his colors and backs up if his right antenna is in water. Hence, he makes a small circle usually on his one tile of land, and as he drifts into the water, he backs up, then resumes his circling pattern. This has given him a natural defense against water which is deadly to pretty much all of my other critters.

As a note, I am using 2 hidden layers in the neural network at the moment, which is just a matter of changing the BRAIN_WIDTH variable in Creature.pde to 4.

**Comment by CrazyPython** [comment]
@AutumnRayne file > edit > click through > submit pull request.

**Comment by AutumnRayne** [comment]
@CrazyPython Thanks. I just set it up. I noticed that even though I only changed 4 lines, it listed that I deleted everything and then re-added it. Is that supposed to happen, or did I do something wrong?

**Comment by CrazyPython** [comment]
@AutumnRayne Dunno. Try recommitting?

**Comment by mbertheau** [comment]
@AutumnRayne thanks for your analysis and fix. I commented on the PR #10.

It's also perfectly ok to submit just a PR, if you have an issue and the fix. You can describe the issue and fix in the PR as well.

I'll close this when the PR is merged :)

Thanks again four your contribution!

**Comment by AutumnRayne** [comment]
Makes sense. Before CrazyPython told me how to make a PR, I didn't even know what they were, so I'll be using them from now on. Thanks for your help in implementing the changes! ^_^

**Comment by CrazyPython** [comment]
@AutumnRayne For any open source project, both internal and external contributions should be formatted as a PR. Do you know how to use git via the command line?

@mbertheau You can write "Closes #8" in the merge commit message and this issue will be instantly closed.

**Comment by CrazyPython** [comment]
@AutumnRayne To be honest, your programming skill isn't so great. Try learning python or building a server w/ Django.

**Comment by Moth-Tolias** [comment]
@crazypython hasn't autumn been finding the majority of the bugs?
seems like their skill is just fine to me

**Comment by YoYoYonnY** [comment]
Changes have been commited, closing.

**Comment by YoYoYonnY** [comment]
@CrazyPython Cool, I did not know that.

**Comment by martijnvans** [comment]
@crazypython Why you hatin?  @AutumnRayne is doing great stuff. >:(

**Comment by mbertheau** [comment]
@CrazyPython I agree with @Moth-Tolias and @martijnvans . Please try to stay positive and respectful in all communication here. @AutumnRayne has indeed found and fixed important bugs. He or she may not be as familiar with git and GitHub as you. All that is irrelevant when it comes to our choice of words. Thank you for your understanding :)

**Comment by israelraizer** [comment]
CrazyPython has been pretty harsh on people lately... besides, why should AutumnReye learn Python? What does Python have to do with Evolv.io if it was written in Java?

**Comment by CrazyPython** [comment]
@mbertheau Sorry if that came off as mean. I just offered some advice.

**Comment by joker314** [comment]
@CrazyPython You didn't "just" do that; you also insulted their coding abilities

**Comment by UnknownEvil** [comment]
@joker314 This is from more than a year ago, silly
