### ISSUE TITLE
Unity port

### ISSUE THREAD

**Issue by S-Hodgson-MMOARgames** [evolvio/evolv.io#88]
Hey guys,

Started a port of Evolv.io to the Unity engine if anyone's interested.
https://github.com/S-Hodgson-MMOARgames/Evolv.io-Unity

**Comment by casprussian** [comment]
Eh, i don't like the portability/licence problems of unity

**Comment by S-Hodgson-MMOARgames** [comment]
Portability I can understand. But licensing? I'm not sure what you mean.

**Comment by casprussian** [comment]
@S-Hodgson-MMOARgames Unity doesn't do well on *nix. Also, Unity isn't a free platform, and I'd rather stay close to an open standard like Processing and Java that will stay strong. Dependence on Unity is dependence on the sponsors of Unity and there's also a lot of legal concerns.

**Comment by S-Hodgson-MMOARgames** [comment]
Ahh, no worries. Well then do your own thing. I just wanted to share.

**Comment by NateUniAccount** [comment]
Thanks for sharing! Gonna close this issue though as it seems to be settled
