### ISSUE TITLE
Sorting by Lowest Gen doesn't work

### ISSUE THREAD

**Issue by NateUniAccount** [evolvio/evolv.io#96]
Sorting by all algorithms work, apart from lowest gen.
I believe the method used for sorting is the Creature.measure(int choice) method
This needs to be looked at and fixed

**Comment by PRabahy** [comment]
I looked at the sorting code a while ago, and its all pretty ugly to me. It should probably take a general purpose comparison function instead of special casing several sorting possibilities. I guess that scope is quite a bit larger than just fixing this big.

**Comment by NateUniAccount** [comment]
I believe it may actually work but the generations haven't built up enough to change while I was testing it

**Comment by NateUniAccount** [comment]
It does actually work, closing this issue
